expose local_error to applications
cloudflare/quiche pull request #1025
Opened 2021-08-18 02:57 UTC by kevinjohna6

Closes #1023.

2021-08-18 11:31 UTC, LPardue requested changes

2021-08-18 11:31 UTC, LPardue commented on include/quiche.h
> +// Returns true if a connection error was queued, and updates the provided
```suggestion
// Returns true if a connection error was queued or sent, and updates the provided
```

2021-08-18 11:31 UTC, LPardue commented on src/lib.rs
> +    /// Note that a `Some` return value does not necessarily imply
We should also note that quiche can internally close connections, so a value might be returned even if the user/app didn't call `close()` explicitly.

2021-08-18 11:31 UTC, LPardue commented on src/lib.rs
> +        assert_eq!(pipe.server.close(true, 0x1234, b"hello!"), Ok(()));
Please add a check before `close()` is called too.

2021-08-18 21:19 UTC, LPardue approved these changes

2021-08-23 11:35 UTC, merged

2021-08-23 11:35 UTC, ghedo commented
Merged, thanks @kevinjohna6!