qlog: update docs and bump to 0.6.0
cloudflare/quiche pull request #1137
Opened 2022-01-24 20:09 UTC by LPardue

2022-01-24 20:23 UTC, LPardue commented
builds failing on quiche not being able to pull qlog 0.6.0 from crates.io

2022-01-24 20:53 UTC, LPardue commented
fixed now I published it :)

2022-01-25 12:36 UTC, ghedo requested changes
Looks like some empty lines were missed in the README, otherwise lgtm.

2022-01-25 12:36 UTC, ghedo commented on qlog/README.md
> +### Creating a TraceSeq
```suggestion

### Creating a TraceSeq

```

2022-01-25 12:36 UTC, ghedo commented on qlog/README.md
> +## Streaming Traces JSON Text Sequences (JSON-SEQ)
```suggestion
## Streaming Traces JSON Text Sequences (JSON-SEQ)

```

2022-01-25 12:36 UTC, ghedo commented on qlog/README.md
> +utilities that aid streaming.
```suggestion
utilities that aid streaming.

```

2022-01-25 12:36 UTC, ghedo commented on qlog/README.md
> +data in the [`Event`] array.
```suggestion
data in the [`Event`] array.

```

2022-01-25 12:36 UTC, ghedo commented on qlog/README.md
> +### Creating a Trace
```suggestion

### Creating a Trace
```

2022-01-25 14:54 UTC, ghedo approved these changes

2022-01-25 14:55 UTC, merged