h3: initial support for PRIORITY_UPDATE frame
cloudflare/quiche pull request #1155
Opened 2022-02-04 20:47 UTC by LPardue

This PR builds on top of the initial PRIORITY_UPDATE frame support PR https://github.com/cloudflare/quiche/pull/1139 

The additional commit adds a new Event::PriorityUpdate that is returned by the
`poll()` method. It only occurs on servers because only clients can send
PRIORITY_UPDATE frames.

Event:PriorityUpdate behaves like other edge-triggered events. The first
time a server receives a PRIORITY_UPDATE frame, the event is fired and
subsequent `poll()` will not generate more events. Application are
required to use the new `recv_priority_update()` method to read all
received PRIORITY_UPDATE frames before the trigger is rearmed.

PRIORITY_UPDATE frames are sent on the control stream and include a
reference to request stream IDs. Due to reordering, it is possible that
a PRIORITY_UPDATE frame can be received before the HEADERS of the
request. Because there are no ordering guarantees at the wire, the
ordering of events is unimportant. This commit chooses to present
Event::PriorityUpdate ahead of other events.

Clients might send multiple PRIORITY_UPDATE frames between server reads,
but only the most up to date value matters. To accommodate this, only
the single most recent PRIORITY_UPDATE is stored in quiche until it is
read via `recv_priority_update()`.

Although, PRIORITY_UPDATE frames can reference streams unknown at the
server (see above). There are limits to the streams that they refer to.
A PRIORITY_UPDATE frame that exceeds the server's maximum bidi stream ID
is treated as an error, as defined in the spec. A PRIORITY_UPDATE that
refers to a collected stream is completely ignored and will not cause an
Event::PriorityUpdate to be generated. In order to apply these
restrictions, the quiche library has had a minor change to expose the
required information about streams.

2022-02-04 21:25 UTC, LPardue commented
I forgot about the FFI. Pushed a place holder change there. But it made me realise we might want to consider treating the Priority Field Value as a colletion of `u8` rather than a `String`. I'll think on that a bit more.

2022-04-11 01:12 UTC, LPardue commented
I pushed a tweak to the API so that a PriorityUpdate event is returned once per stream, until the value is read via recv_priority_update() (causing that stream's trigger is then rearmed). This allow apps to store information about the fact there is a PRIORITY_UPDATE, without requiring them to actually retrieve that directly and consume or store it.

2022-04-12 23:56 UTC, LPardue commented
Some further tweaks after IRL chat

2022-05-09 13:18 UTC, ghedo requested changes
Added a couple of comments, but looks ok overall.

2022-05-09 15:25 UTC, LPardue commented on quiche/src/lib.rs
> +    pub fn local_max_streams_bidi(&self) -> u64 {
agree, removed both of these

2022-05-10 17:03 UTC, ghedo approved these changes

2022-05-10 17:03 UTC, merged