WIP: delivery_rate: draft 01
cloudflare/quiche pull request #1158
Opened 2022-02-16 10:38 UTC by junhochoi

- Update delivery rate implementation to draft 01.
- Major rework on delivery rate estimation.
- Expose some functions for later use, such as
  recovery.delivery_rate.update_app_limited(),
  recovery.delivery_rate.app_limited(),
  recovery.delivery_rate.delivered(),
  recovery.delivery_rate.rate_sample_is_app_limited().

TODOs
- [ ] fix app_limited
- [ ] update test

2022-03-03 00:31 UTC, junhochoi commented
@lohith-bellad PTAL

2022-03-03 14:10 UTC, ghedo requested changes
Did an initial review and added some comments, but I'll probably need to do another pass.

Also:

> When pacing is not used in the application, this doesn't have an impact because the application will ignore the pacing rate.

Note that delivery rate is also exposed as part of `Stats`, so I guess if an application doesn't do pacing that value will be inaccurate? Probably not a big problem though, just want to clarify this.

2022-03-03 14:10 UTC, ghedo commented on quiche/src/recovery/delivery_rate.rs
> +                // Use the longer of the send_elapsed and ack_elapsed.
This is kinda self evident, no need to comment.

2022-03-03 14:11 UTC, ghedo commented
Also need to rebase now, since the other PR was merged.

2022-03-03 22:13 UTC, junhochoi commented
> > When pacing is not used in the application, this doesn't have an impact because the application will ignore the pacing rate.
> 
> Note that delivery rate is also exposed as part of `Stats`, so I guess if an application doesn't do pacing that value will be inaccurate? Probably not a big problem though, just want to clarify this.

Possibly yes -- if we want to be more accurate without pacing, I think it's better make an API (pacing on/off) controlling the behavior (recording Sent.time_sent with paced time or not).

2022-03-03 22:14 UTC, junhochoi commented on quiche/src/recovery/delivery_rate.rs
> +            self.first_sent_time = Some(now);
Updated.

2022-03-03 22:17 UTC, junhochoi commented on quiche/src/recovery/delivery_rate.rs
> +    pub fn update_rate_sample(&mut self, pkt: &Acked, now: Instant) {
Acked packet never come back again in QUIC because QUIC uses monotinic increasing packet number, so I don't think we need this.

2022-03-03 22:20 UTC, junhochoi commented on quiche/src/recovery/delivery_rate.rs
> +    pub fn rs_delivery_rate(&self) -> u64 {
SGTM - I renamed rs_ prefix to sample_

2022-03-07 19:27 UTC, junhochoi commented on quiche/src/recovery/delivery_rate.rs
> +            self.rate_sample.largest_acked = pkt.pkt_num;
I removed `RateSample.largest_acked` -- it seems we don't need it.

2022-03-08 12:10 UTC, ghedo commented
I added a commit to tweak some commentrs slightly, and also to add a note to the `Stats.delivery_rate` documentation about pacing (I don't think it's worth adding a whole new configuration option just to make this more accurate, but it's good to at least document the potential problem).

2022-03-08 12:14 UTC, ghedo approved these changes

2022-03-08 12:22 UTC, merged