Make qlog packet event logging atomic
cloudflare/quiche pull request #1161
Opened 2022-02-18 17:18 UTC by LPardue

When we switched from JSON to JSON-SEQ, we modified the qlog serializer but didn't change it's behaviour wrt QUIC Packet events (rx/tx). The old behaviour TL;DR was:

1. qlog streamer user passes streamer a packet event
2. Streamer writes out packet header information. Then it locks itself into frame writing mode.
2. While locked, no other events cand be written.
3. qlog streamer user passes 0 or more frames.
4. qlog streamer user finalizes frames write. Streamer unlocks itself.

There are a few downsides to that approach:

* Locking prevents other events being written. For example, while processing frames, any additional events would be ignored by the serializer. While callers could buffer events themselves and log them later, it adds complication and we decided never to do that inside quiche.
* Related to the above. We had several places where processing might shortcircuit or terminate. We ended up peppering quiche with calls to finalize frame writing.
* It's possible to produce an incomplete log line if the connection is destroyed before.
* It's less efficient to write a partial JSON object out.

The changes in the PR make packet event logging atomic. The qlog streamer is simplified by removing all locking and frame-specific logic. As a consequence, the quiche library requires updates in the packet send() and receive() function. Rather than serialize individual frames as they are added or read from a packet, we buffer the qlog representation of a frame, and then later pass that in a single call to the streamer.

2022-02-28 12:42 UTC, ghedo requested changes

2022-02-28 12:42 UTC, ghedo commented on quiche/src/lib.rs
> +        let mut qlog_frames = self.qlog.streamer.as_ref().map(|_| vec![]);
I don't think there's much point in making this an Option, as `qlog_with_type!()` will already skip the push calls if there is no qlog streamer, and just calling `Vec::new()`/`vec![]` unconditionally shouldn't really do much harm.

2022-02-28 12:42 UTC, ghedo commented on quiche/src/lib.rs
> +        let mut qlog_frames = self.qlog.streamer.as_ref().map(|_| vec![]);
Same as above.

2022-04-12 13:44 UTC, ghedo requested changes
Added a nit, but looks good otherwise.

2022-04-12 13:44 UTC, ghedo commented on quiche/src/lib.rs
> +        let mut qlog_frames = vec![];
```suggestion
        let mut qlog_frames = Vec::with_capacity(frames.len());
```

2022-04-12 14:48 UTC, LPardue commented on quiche/src/lib.rs
> +        let mut qlog_frames = vec![];
applied, thanks!

2022-04-12 14:58 UTC, ghedo approved these changes

2022-04-18 14:49 UTC, merged