quic: bound consecutive non ack-eliciting packet sends
cloudflare/quiche pull request #1312
Opened 2022-09-06 20:00 UTC by ehaydenr

2022-09-06 20:35 UTC, LPardue commented on quiche/src/lib.rs
> +            .get_mut(send_pid)?
why do we need `get_mut`?

2022-09-06 20:53 UTC, ehaydenr commented on quiche/src/lib.rs
> +            .get_mut(send_pid)?
thank you! - fixed

2022-09-06 21:50 UTC, junhochoi approved these changes

2022-09-07 11:52 UTC, ghedo requested changes

2022-09-07 11:52 UTC, ghedo commented on quiche/src/lib.rs
> +        if self.paths.get(send_pid)?.recovery.should_elicit_ack(epoch) &&
https://github.com/cloudflare/quiche/blob/master/quiche/src/lib.rs#L3301 should be updated too I think?

Also, we can cache the value in a local `should_elicit_ack` variable or something, so we don't need to put this ultra-long method call in the condition itself (just for readability's sake).

2022-09-07 11:52 UTC, ghedo commented on quiche/src/recovery/mod.rs
> +    /// How many non-ack-eliciting packets have been sent
```suggestion
    /// How many non-ack-eliciting packets have been sent.
```

2022-09-07 11:52 UTC, ghedo commented on quiche/src/lib.rs
> +                return;
Might be a good idea to check that this happens after 24 packets? e.g. can change the `_` in the for loop to a variable, and then do `assert_eq!(i, 24)` or something like that.

2022-09-07 15:28 UTC, ghedo commented on quiche/src/lib.rs
> +        if self.paths.get(send_pid)?.recovery.should_elicit_ack(epoch) &&
@ehaydenr I think the comment about https://github.com/cloudflare/quiche/blob/master/quiche/src/lib.rs#L3301 still needs addressing? Can just move the `should_elicit_ack` variable up and re-use it there too.

2022-09-08 06:57 UTC, ghedo approved these changes

2022-09-08 06:57 UTC, merged