h3: exit early is the QUIC connection is not a suitable state
cloudflare/quiche pull request #1339
Opened 2022-10-03 15:58 UTC by LPardue

2022-10-03 16:14 UTC, jyn514 approved these changes
Thank you!

2022-10-07 07:22 UTC, ghedo requested changes

2022-10-07 07:22 UTC, ghedo commented on quiche/src/h3/mod.rs
> +            trace!("QUIC connection must be established or in early data before creating an HTTP/3 connection.");
```suggestion
            trace!("{} QUIC connection must be established or in early data before creating an HTTP/3 connection", conn.trace_id());
```

2022-10-07 07:43 UTC, ghedo approved these changes

2022-10-07 07:43 UTC, merged