fix #1424 -- pn are now encoded in 3 bytes when 2^24 <= pn < 2^32
cloudflare/quiche pull request #1431
Opened 2023-03-03 22:34 UTC by frochet

2023-03-25 02:35 UTC, LPardue submitted a review, later dismissed
LGTM

2023-03-25 03:25 UTC, ghedo requested changes

2023-03-25 03:25 UTC, ghedo commented on quiche/src/packet.rs
> +
```suggestion
```

2023-03-25 03:25 UTC, ghedo approved these changes

2023-03-30 06:33 UTC, merged

2023-03-30 06:34 UTC, ghedo commented
Merged, thanks @frochet!