Convert Instant to timespec in a more safer way
cloudflare/quiche pull request #1483
Opened 2023-04-17 17:16 UTC by lohith-bellad

Different architectures have different sizes for timespec and Instant. ~~Here conversion is considered only for x86_64 architectures running linux. Not sure if other architectures are using paced time (because earlier conversion had problems and using it would have raised bug reports) . If any architecture is found using paced time then conversion for that arch should be added.~~ This diff covers all of them.

2023-04-17 17:17 UTC, LPardue submitted a review, later dismissed

2023-04-17 17:25 UTC, ghedo requested changes

2023-04-17 17:25 UTC, ghedo commented on quiche/src/ffi.rs
> +    const TO_TIMESPEC: i64 = 1_000_000_000;
```suggestion
    const NANOS_PER_SEC: u64 = 1_000_000_000;
```

2023-04-17 17:25 UTC, ghedo commented on quiche/src/ffi.rs
> +    out.tv_sec = raw_time / TO_TIMESPEC;
```suggestion
    out.tv_sec = (raw_time / NANOS_PER_SEC) as i64;
```

2023-04-17 17:25 UTC, ghedo commented on quiche/src/ffi.rs
> +    out.tv_nsec = raw_time % TO_TIMESPEC;
```suggestion
    out.tv_nsec = (raw_time % NANOS_PER_SEC) as i64;
```

2023-04-17 17:25 UTC, ghedo commented on quiche/src/ffi.rs
> +    let raw_time = time.duration_since(INSTANT_ZERO).as_nanos() as i64;
```suggestion
    let raw_time = time.duration_since(INSTANT_ZERO).as_nanos();
```

2023-04-18 15:25 UTC, ghedo approved these changes

2023-04-18 15:26 UTC, merged