recovery: make initial CWND configurable
cloudflare/quiche pull request #1588
Opened 2023-08-15 16:51 UTC by evanrittenhouse

2023-08-15 17:35 UTC, LPardue requested changes

2023-08-15 17:35 UTC, LPardue commented on quiche/src/lib.rs
> +    /// Sets the number of packets to be sent in the initial congestion window.
```suggestion
    /// Sets initial congestion window size in terms of packet count.
```

2023-08-15 17:35 UTC, LPardue commented on quiche/src/lib.rs
> +// The default number of packets sent in the initial congestion window.
```suggestion
// The default initial congestion window size in terms of packet count.
```

2023-08-15 17:35 UTC, LPardue commented on quiche/include/quiche.h
> +// Sets the initial cwnd for the connection.
```suggestion
// Sets the initial cwnd for the connection in terms of packet count.
```

2023-08-15 17:35 UTC, LPardue commented on quiche/src/recovery/mod.rs
> +    /// How many packets should be sent in the initial congestion window.
```suggestion
    /// Initial congestion window size in terms of packet count
```

2023-08-17 17:36 UTC, evanrittenhouse commented
To test, I set `DEFAULT_INITIAL_CONGESTION_WINDOW_PACKETS` to 30 and checked QVIS on a 90 KB image. You can see here the difference between the two:

#### ICWND = 10
![testing_icwnd_10](https://github.com/cloudflare/quiche/assets/84083822/1f76448d-576c-480f-80a1-14e146f89c95)

#### ICWND = 30
![testing_icwnd_30](https://github.com/cloudflare/quiche/assets/84083822/6969bdab-a80b-4918-8053-851c2bb0ba91)

2023-08-17 20:22 UTC, LPardue approved these changes

2023-08-18 02:10 UTC, junhochoi commented
👍 might be beneficial to add a configurable option to quiche-server/client for easier testing.

2023-08-18 20:36 UTC, evanrittenhouse commented
Checked QVIS logs with `--initial-cwnd-packets 10` and `--initial-cwnd-packets 30` on both quiche-server and quiche-client. We see similar results as before:

**IWND = 10**
<img width="1462" alt="icwnd_10" src="https://github.com/cloudflare/quiche/assets/84083822/e9924a20-539a-4b50-b955-94a684af70c4">

**IWND = 30**
<img width="1470" alt="icwnd_30" src="https://github.com/cloudflare/quiche/assets/84083822/1f428818-a1d8-4f03-b5c6-33cb686e4b8b">

2023-08-22 10:25 UTC, ghedo approved these changes

2023-08-22 10:25 UTC, merged