openssl/quictls support WIP
cloudflare/quiche pull request #1605
Opened 2023-08-29 10:57 UTC by brbzull0

Apache Traffic Server uses this library for handling the QUIC side of things of H3, as a part of this effort we plan to use quictls as the  cryptography  library, this is an effort to support that.

---

This is a **WIP DRAFT** that follows up the previous work done in the [openssl](https://github.com/cloudflare/quiche/tree/openssl) branch.  This is not yet a PR quality code, I'll be adjusting this a bit, also the feature compilation switch(`cfg(feature = "openssl")`) is a bit of a mess, so I will be addressing these two(force pushing) among other things.
This is my first attemt on Rust, so please feel free to provide any feedback.

It would be ideal to  get feedback on the design part of the things as it looks like the enc/dec flow was designed to be used with the BoringSSL API which is much simpler than the openssl one and uses different technique than the openssl api, like buffer pointer alias for the in/out, so because of this I had to do some tricks to work with the openssl API.
I did run some very basic smoke tests locally but I will be doing some more tests.

### openssl/quictls API changes

High level list of features I'll be working on:

- [x] AEAD
- [ ] Early Data. (probably for a different PR)
- [x] SSL_SESSION serialization.

There is also some functions that seems to be used for logging only that have low priority for now:
 - SSL_get_curve_id
 - SSL_get_peer_signature_algorithm

Certificates:
- SSL_get0_peer_certificates is used by the C api.

also:
 - SSL_CTX_set_verify (available in openssl)
 - etc

Compilation warning(unused functions depending what you use to build(bssl/ossl) will be fixed also.

Any feedback will be appreciated.

### building notes

Make sure you have the openssl library in your `LD_LIBRARY_PATH`

### Additional notes

This branch is base on an early [commit](https://github.com/cloudflare/quiche/commit/94a2640a941af513104feb6b4419059c04bd579c) as latest master would break my testing bench which uses Apache Traffic Server.
After this code gets finished and polished I will be making an official PR.

2023-11-13 12:28 UTC, brbzull0 commented
CI need to include openssl/quictls so we know we are passing all build/tests with the each vendor.

2024-01-06 05:44 UTC, Eimji commented
Hello,

I am working on a mobile application which allows to use encrypted DNS (Android for the moment, iOS right after). 
I tested quiche with a little proto on Android, it works great (thanks!). So I wanted to integrate quiche into my application to develop DoQ and DoH3, but I got compilation errors  due to conflicts with OpenSSL. Yes, I use OpenSSL 3.2 to enable DoT and DoH.

It would be great if we can have a pluggable TLS vendor. 

@brbzull0 As OpenSSL 3.2 supports now QUIC (not all features), your PR will support legacy OpenSSL > 3.2 or only quictls? Thanks for your work.

2024-01-11 13:29 UTC, brbzull0 commented
> Hello,
> 
> I am working on a mobile application which allows to use encrypted DNS (Android for the moment, iOS right after). I tested quiche with a little proto on Android, it works great (thanks!). So I wanted to integrate quiche into my application to develop DoQ and DoH3, but I got compilation errors due to conflicts with OpenSSL. Yes, I use OpenSSL 3.2 to enable DoT and DoH.
> 
> It would be great if we can have a pluggable TLS vendor.
> 
> @brbzull0 As OpenSSL 3.2 supports now QUIC (not all features), your PR will support legacy OpenSSL > 3.2 or only quictls? Thanks for your work.

Hello @Eimji . The plan is only quictls for now. Thanks for having a look

2024-01-11 13:29 UTC, brbzull0 commented
Making this ready for review so we can gather some input. Thanks.

2024-03-04 19:00 UTC, brbzull0 commented
I think is worth having [this](https://github.com/quictls/openssl/issues/138) link here, in case we want to discuss about it.

2024-03-12 16:28 UTC, ghedo submitted a review, later dismissed

2024-03-12 18:10 UTC, LPardue requested changes
A few nits but overall looks good

2024-03-12 18:10 UTC, LPardue commented on quiche/src/crypto/boringssl.rs
> +// be kept in sync.
Should we add the commit ID in the comment to make tracking more easy?

2024-03-12 18:10 UTC, LPardue commented on quiche/src/crypto/mod.rs
> +            packet: PacketKey::from_secret(aead, &secret, 1)?,
```suggestion
            packet: PacketKey::from_secret(aead, &secret, Self::ENCRYPT)?,
```

2024-03-12 18:10 UTC, LPardue commented on quiche/src/h3/mod.rs
> +    #[cfg(not(feature = "openssl"))]
```suggestion
    #[cfg(not(feature = "openssl"))] // 0-RTT not supported when using openssl/quictls
```

2024-03-12 18:10 UTC, LPardue commented on quiche/src/lib.rs
> +    // openssl does not provide a straight interface to deal with custom
```suggestion
    // openssl does not provide a straightforward interface to deal with custom
```

2024-03-12 18:10 UTC, LPardue commented on quiche/src/tls/openssl_quictls.rs
> +        println!("## calling  set_early_data_enabled context!!")
hangover that needs cleanup. Probably a noop or maybe an assert?

2024-03-16 05:36 UTC, ghedo approved these changes

2024-03-16 05:41 UTC, LPardue approved these changes

2024-03-16 05:41 UTC, merged

2024-03-16 05:42 UTC, ghedo commented
@brbzull0 I was going to do it, just got delayed by travel. Thanks for your work, this is merged now!

2024-03-18 09:11 UTC, brbzull0 commented
> @brbzull0 I was going to do it, just got delayed by travel. Thanks for your work, this is merged now!

great stuff!
@ghedo @LPardue  Thanks a lot gents!