When using packet pacing at the lower layers there can be less data
cloudflare/quiche pull request #1636
Opened 2023-10-24 22:56 UTC by lohith-bellad

in the network than in_flight data. This is due to buffering the packets at lower layers until the sent time of the packet. When using BBR as the CC algorithm and when we are checking the condition to exit the drain phase we need to consider only the data which is in the network and not the data buffered in the host. If we consider the inflight(host buffered
+ in the network) data then we exit the drain phase later than expected leading to low throughput.

2023-10-24 23:01 UTC, LPardue commented on quiche/src/recovery/bbr/per_ack.rs
> +    println!("est = {:?}", bbr_inflight(r, 1.0));
nit: leftover

2023-10-24 23:06 UTC, lohith-bellad commented on quiche/src/recovery/bbr/per_ack.rs
> +    println!("est = {:?}", bbr_inflight(r, 1.0));
fixed it!

2023-10-25 09:48 UTC, ghedo requested changes

2023-10-25 09:48 UTC, ghedo commented on quiche/src/recovery/mod.rs
> +            for pkt in self.sent[epoch].iter() {
This needs to exclude packets that have already been acked or lost as they are not immediately removed from the list, as well as include only packets that are actually "in-flight".

I think the inner loop can be replaced with something like:
```rust
            buffered += sent
                // Skip packets that have already been sent, acked or lost, or that are not in-flight.
                .filter(|p| p.in_flight && p.time_acked.is_none() && p.time_lost.is_none() && p.time_sent > now)
                .map(|x| x + p.size);
```
(not entirely sure it actually compiles though)

2023-10-25 09:48 UTC, ghedo commented on quiche/src/recovery/mod.rs
> +            in_flight: true,
We should also add checks for a packet that is not in-flight.

2023-10-25 09:48 UTC, ghedo commented on quiche/src/recovery/mod.rs
> +        // Send the third packet out.
```suggestion
        // Send the fourth packet out.
```

2023-10-25 09:48 UTC, ghedo commented on quiche/src/recovery/mod.rs
> +        // send out first packet (a full initcwnd).
```suggestion
        // Send out the first packet (a full initcwnd).
```

2023-10-26 08:52 UTC, junhochoi commented on quiche/src/recovery/bbr/mod.rs
> +
This might change the result of functions using bytes_in_flight in bbr_update_model_and_state(). Is this a necessary change?

2023-10-26 08:54 UTC, junhochoi commented on quiche/src/recovery/mod.rs
> +        cfg.set_cc_algorithm(CongestionControlAlgorithm::CUBIC);
Should we test it with BBR CC?

2023-10-26 09:00 UTC, junhochoi commented
It seems this PR ports some of linux bbr code (`bbr_packets_in_net_at_edt()`)? If so, it is used in 2 places including this change, you might want to take a look at https://github.com/torvalds/linux/blob/611da07b89fdd53f140d7b33013f255bf0ed8f34/net/ipv4/tcp_bbr.c#L569C2-L569C2 too (bbr_is_next_cycle_phase).

2024-01-11 18:37 UTC, closed without merging