H3: if readable after Finished, call recv again
cloudflare/quiche pull request #1796
Opened 2024-06-06 16:37 UTC by vkrasnov

If an H3 stream gets into a Data state that is not cleared for the stream (for example because downward backpressure), and a ResetStream arrives, the poll will transition the stream to finished and never clear the readable state of the stream, it will forever stuck in the readable state. This will mean that poll will return Finished and not Reset for the stream, and will have a somewhat significant performance impact, as for long lived connections it will take longer and longer to poll before the iterator reaches a stream that is actually readable.

2024-06-07 10:35 UTC, ghedo requested changes

2024-06-07 10:35 UTC, ghedo commented on quiche/src/h3/mod.rs
> +                // The connection is finished, but is still readable, it may
```suggestion
                // The stream is finished, but is still readable, it may
```

2024-06-07 10:35 UTC, ghedo commented on quiche/src/h3/mod.rs
> +        // Client sends HEADERS and doesn't fin
```suggestion
        // Client sends HEADERS and doesn't fin.
```

2024-06-07 10:35 UTC, ghedo commented on quiche/src/h3/mod.rs
> +        // Server receives headers and data
```suggestion
        // Server receives headers and data...
```

2024-06-07 10:35 UTC, ghedo commented on quiche/src/h3/mod.rs
> +        // ..then Client sends RESET_STREAM
```suggestion
        // ..then Client sends RESET_STREAM.
```

2024-06-07 10:35 UTC, ghedo commented on quiche/src/h3/mod.rs
> +        // Server receives the reset and there are no more readable streams
```suggestion
        // Server receives the reset and there are no more readable streams.
```

2024-06-07 10:36 UTC, ghedo approved these changes
LGTM, only applied some minor fixes to comments.

2024-06-07 10:38 UTC, ghedo commented
Also, waiting for @LPardue to look at this too before merging.

2024-06-11 16:39 UTC, LPardue approved these changes

2024-06-11 16:41 UTC, merged