Expose Connection::stream_priority in C API
cloudflare/quiche pull request #723
Opened 2020-11-14 08:55 UTC by kachayev

Added `quiche_conn_stream_priority` to FFI. Covers #721.

2020-11-14 15:41 UTC, LPardue submitted a review, later dismissed
Thanks! Lgtm.

2020-11-16 21:52 UTC, ghedo requested changes
Added a minor nitpick. Looks good otherwise, thanks!

2020-11-16 21:52 UTC, ghedo commented on include/quiche.h
> +// Set the priority for a stream.
```suggestion
// Sets the priority for a stream.
```
(to match the `Connection::stream_priority()` Rust docs)

2020-11-17 08:23 UTC, ghedo approved these changes

2020-11-17 08:24 UTC, merged

2020-11-17 08:24 UTC, ghedo commented
Merged, thanks @kachayev!