Add peer_max_streams_bidi() and peer_max_streams_uni()
cloudflare/quiche pull request #784
Opened 2020-12-11 19:33 UTC by normanmaurer

Motivation:

Sometimes its useful to know if a stream creation would be allowed before actual trying to create the stream.

Modifications:

Add peer_max_streams_bidi() and peer_max_streams_uni() that can be used to check for the maximum allowed stream id by the remote peer.

Result:

Fixes https://github.com/cloudflare/quiche/issues/734

2020-12-11 19:34 UTC, normanmaurer commented
/cc @bagder ... I think this would also help you for https://github.com/cloudflare/quiche/issues/397

2020-12-14 12:20 UTC, ghedo commented
These functions will simply return what the maximum number of streams the peer allows, they don't say anything about whether the application is actually allowed to create new ones, so the application would need to keep track of how many streams it already opened on its own, which seems unnecessary given that quiche already does it anyway.

So I think we should add functions to return the remaining number of streams allowed (i.e. "max count - how many we already created").

2020-12-14 12:32 UTC, normanmaurer commented
@ghedo that would work for me as well... should I adjust this PR and ping you once done ?

2020-12-15 13:16 UTC, ghedo commented
Feel free to update the PR. The functions should also be renamed I think to something that better reflects the new bahviour, but I can't think of anything good right now. We can do this later anyway.

2020-12-16 11:21 UTC, normanmaurer commented
@ghedo wdyt about this one ? I will squash and adjust the commit message once all is ok.

2021-01-11 07:14 UTC, normanmaurer commented
Anything else I need to do to help pushing this over the finish line ?

2021-01-25 14:27 UTC, ghedo requested changes
The code looks good to me now, I just don't particularly like the API names, maybe something like `peer_streams_left_bidi/uni()`?

Also, added some nits.

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// Returns the amount of bidirectional streams that can be created
```suggestion
    /// Returns the number of bidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// before the stream count limit is reached.
```suggestion
    /// before the peer's stream count limit is reached.
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// Returns the amount of unidirectional streams that can be created
```suggestion
    /// Returns the number of unidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// before the stream count limit is reached.
```suggestion
    /// before the peer's stream count limit is reached.
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// This can be useful to know if its possible to create a unidirectional
```suggestion
    /// This can be useful to know if it's possible to create a unidirectional
```

2021-01-25 14:27 UTC, ghedo commented on include/quiche.h
> +// Returns the amount of bidirectional streams that can be created
```suggestion
// Returns the number of bidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on include/quiche.h
> +// before the stream count limit is reached.
```suggestion
// before the peer's stream count limit is reached.
```

2021-01-25 14:27 UTC, ghedo commented on include/quiche.h
> +// Returns the amount of unidirectional streams that can be created
```suggestion
// Returns the number of unidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on include/quiche.h
> +// before the stream count limit is reached.
```suggestion
// before the peer's stream count limit is reached.
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// This can be useful to know if its possible to create a bidirectional
```suggestion
    /// This can be useful to know if it's possible to create a bidirectional
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// stream or not without trying it first.
```suggestion
    /// stream without trying it first.
```

2021-01-25 14:27 UTC, ghedo commented on src/lib.rs
> +    /// stream or not without trying it first.
```suggestion
    /// stream without trying it first.
```

2021-01-25 14:27 UTC, ghedo commented on src/stream.rs
> +    /// Returns the amount of bidirectional streams that can be created
```suggestion
    /// Returns the number of bidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on src/stream.rs
> +    /// before the stream count limit is reached.
```suggestion
    /// before the peer's stream count limit is reached.
```

2021-01-25 14:27 UTC, ghedo commented on src/stream.rs
> +    /// Returns the amount of unidirectional streams that can be created
```suggestion
    /// Returns the number of unidirectional streams that can be created
```

2021-01-25 14:27 UTC, ghedo commented on src/stream.rs
> +    /// before the stream count limit is reached.
```suggestion
    /// before the peer's stream count limit is reached.
```

2021-01-25 14:43 UTC, LPardue commented
Changes look fine but could we add some unit tests that exercise the limits decreasing / increasing as a client an server interact? It'd be good to know how this behaves in the intended usage case, such as an application seeing 0 streams and then waiting a bit for some to open up.

2021-01-25 17:12 UTC, normanmaurer commented
@LPardue on it...

2021-01-26 08:19 UTC, normanmaurer commented
@LPardue @ghedo tests added... the error for in the workflow seems like not related to this change

2021-01-26 08:35 UTC, normanmaurer commented
```
Run curl -O https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
7
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
8
                                 Dload  Upload   Total   Spent    Left  Speed
9

10
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
11
  5  994M    5 52.8M    0     0   172M      0  0:00:05 --:--:--  0:00:05  171M
12
 25  994M   25  253M    0     0   194M      0  0:00:05  0:00:01  0:00:04  194M
13
 49  994M   49  488M    0     0   211M      0  0:00:04  0:00:02  0:00:02  211M
14
 70  994M   70  698M    0     0   210M      0  0:00:04  0:00:03  0:00:01  210M
15
 82  994M   82  821M    0     0   171M      0  0:00:05  0:00:04  0:00:01  171M
16
 91  994M   91  910M    0     0   171M      0  0:00:05  0:00:05 --:--:--  171M
17
100  994M  100  994M    0     0   170M      0  0:00:05  0:00:05 --:--:--  163M
18
curl: (16) Error in the HTTP2 framing layer
19
Error: Process completed with exit code 16.
```

2021-01-26 10:31 UTC, ghedo approved these changes

2021-01-26 12:02 UTC, merged

2021-01-26 12:02 UTC, ghedo commented
Merged, thanks @normanmaurer!