Validate that a valid version is specified when create a Config
cloudflare/quiche pull request #920
Opened 2021-05-06 17:42 UTC by normanmaurer

Motivation:

We should validate that the version is valid that was used to create the Config object and if not fail.

Modifications:

- Add validation for the version
- Add some tests

Result:

Version is validated during config creation

2021-05-06 17:45 UTC, normanmaurer commented on src/lib.rs
> +        assert_eq!(Config::new(0xb1bababa).err().unwrap(), Error::UnknownVersion);
used `err().unwrap()` as the `Config` doesn't declare `#[derive(Debug)]`. Not sure if there is a reason for this. If not we could do so and use `unwrap_err()`

2021-05-06 17:51 UTC, normanmaurer commented
The build failure is odd as I didn't change anything related to these files... @ghedo any idea ?

2021-05-06 18:57 UTC, ghedo commented
@normanmaurer most of the failures are because of the new Rust release, see https://github.com/cloudflare/quiche/pull/921, though the formatting lint failure is because of the changes in this PR https://github.com/cloudflare/quiche/pull/920/checks?check_run_id=2520952393 (need to run `cargo +nightly fmt` with latest Rust+rustfmt nightly to fix).

2021-05-06 19:09 UTC, normanmaurer commented
Will fix tomorrow

> Am 06.05.2021 um 20:58 schrieb Alessandro Ghedini ***@***.***>:
> 
> ﻿
> @normanmaurer most of the failures are because of the new Rust release, see #921, though the formatting lint failure is because of the changes in this PR https://github.com/cloudflare/quiche/pull/920/checks?check_run_id=2520952393 (need to run cargo +nightly fmt with latest Rust+rustfmt nightly to fix).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-05-07 15:27 UTC, ghedo requested changes
Thanks @normanmaurer, added a few comments.

2021-05-07 15:27 UTC, ghedo commented on src/lib.rs
> +    version == 0x00000000 ||
The spec is a bit terse, but I think what it's saying is that `0x00000000` is reserved only for use within [version negotiation packets](https://quicwg.org/base-drafts/rfc9000.html#name-version-negotiation-packet), so I don't think we should allow users to configure this version.

2021-05-07 15:27 UTC, ghedo commented on src/lib.rs
> +        }
Nit:
```suggestion
        }

```

2021-05-07 15:27 UTC, ghedo commented on src/lib.rs
> +            .all(|b| (b & 0b0000_1111) == 0b0000_1010)
I _think_ this whole thing could be simplified to just:
```rust
    version & 0xfafafafa == version
```
?

The `0xfafafafa` can then also be declared as a named const, so we don't hardcode it, e.g.
```rust
const RESERVED_VERSION_MASK: u32 = 0xfafafafa
```
or something like that.

2021-05-07 15:27 UTC, ghedo commented on src/lib.rs
> +// See https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#section-15
```suggestion
// See https://quicwg.org/base-drafts/rfc9000.html#section-15
```
:D

2021-05-07 15:34 UTC, normanmaurer commented
@ghedo addressed... thanks!

2021-05-10 09:32 UTC, ghedo approved these changes

2021-05-10 09:33 UTC, merged

2021-05-10 09:33 UTC, ghedo commented
Merged, thanks @normanmaurer!