quiche-client: connectionless udp socket
cloudflare/quiche pull request #947
Opened 2021-05-26 22:07 UTC by junhochoi

Now it uses sendto() and recvfrom(), the socket need to be
connectionless.

Before:
```
[2021-05-26T21:58:46.109658000Z INFO  quiche_apps::client] connecting to 172.16.127.145:8443 from 172.16.127.1:52740 with scid 5e6d2dac34510af3a071466617d450357c844777
thread 'main' panicked at 'send() failed: Os { code: 56, kind: Other, message: "Socket is already connected" }', src/bin/quiche-client.rs:48:39
```

After:
```
[2021-05-26T22:04:21.549094000Z INFO  quiche_apps::client] connecting to 172.16.127.145:8443 from 0.0.0.0:64418 with scid a3ff695193c37da3945c83c8645e585edf7eca89
[2021-05-26T22:04:24.537648000Z INFO  quiche_apps::common] 1/1 response(s) received in 2.986774919s, closing...
[2021-05-26T22:04:24.576217000Z INFO  quiche_apps::client] connection closed, recv=80512 sent=775 lost=0 rtt=1.969746ms cwnd=57531
```

2021-05-27 10:49 UTC, ghedo requested changes
Need to update the examples as well.

2021-05-27 15:31 UTC, junhochoi commented
> Need to update the examples as well.

Sure but it breaks linux client. I think using connect() is a right way. I'll look into more.

2021-05-27 17:27 UTC, junhochoi commented
> > Need to update the examples as well.
> 
> Sure but it breaks linux client. I think using connect() is a right way. I'll look into more.

Ok I was looking a wrong branch... I updated other example clients code (C and Rust) which uses `connect()` as well. Should be good for now.

2021-05-28 08:46 UTC, ghedo approved these changes

2021-05-28 08:48 UTC, merged